# Test your FastAPI endpoints

POST http://127.0.0.1:8000/language-cards/
Content-Type: application/json

{
  "description": null,
  "original_lang": "russian",
  "translation_lang": "english",
  "word": "яблоко",
  "translation": "apple"
}
